[package]
name = "seqrepo"
version = "0.2.1"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Port of (read-only) functionality of biocommons/seqrepo to Rust"
license = "Apache-2.0"
homepage = "https://github.com/bihealth/seqrepo-rs"
readme = "README.md"

[lib]
name = "seqrepo"
path = "src/lib.rs"

[[bin]]
name = "seqrepo-cli"
path = "src/bin.rs"
required-features = ["cli"]

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.23"
clap = { version = "4.1.4", features = ["derive", "env"], optional = true }
clap-verbosity-flag = {version = "2.0.0", optional = true}
log = "0.4.17"
noodles = { version = "0.32.0", features = ["bgzf", "fasta", "core"] }
rusqlite = "0.28.0"
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
textwrap = "0.16.0"
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", optional = true }

[dev-dependencies]
env_logger = "0.10.0"
pretty_assertions = "1.3.0"
temp_testdir = "0.2.3"
test-log = "0.2.11"

[features]
cli = ["dep:clap", "dep:clap-verbosity-flag", "dep:tracing-subscriber"]
full = ["cli"]
